version: '3.7'

services:
  example:
    image: example-image
    build:
      context: .
      args:
        - GIT_USER=
        - ACCESS_TOKEN=
    env_file:
      - ./.env
    networks:
      - shared-network
    ports:
      - "8080:8080"

networks:
  shared-network:
    driver: bridge